INSERT INTO descuentos VALUES (001, 'MARTES', 20);
INSERT INTO descuentos VALUES (002, 'MIERCOLES', 15);
INSERT INTO descuentos VALUES (003, 'JUEVES', 10);
INSERT INTO descuentos VALUES (004, 'VIERNES', 5);
INSERT into descuentos VALUES (5,'SABADO Y DOMINGO',0);