INSERT INTO PLATOS VALUES (1001, 'Choco frito', 10.50, 'choco', 'pescado',1);
INSERT INTO PLATOS VALUES (1002, 'Adobo frito', 10.50, 'Cazon Adobado', 'pescado',1);
INSERT INTO PLATOS VALUES (1003, 'Pijotas', 12.50, 'Pijota fritas', 'pescado',1);
INSERT INTO PLATOS VALUES (1004, 'Boquerones', 14.50, 'Boquerones fritos', 'pescado',1);
INSERT INTO PLATOS VALUES (1005, 'Acedias', 16.50, 'Acedias fritas', 'pescado',1);
INSERT INTO PLATOS VALUES (1106, 'Rape Frito', 15.50, 'Rape Frito', 'pescado',1);
INSERT INTO PLATOS VALUES (1101, 'Pez Espada', 18.50, 'Pez Espada Planca con ensalada', 'pescado',1);
INSERT INTO PLATOS VALUES (1102, 'Lenguado', 18.50, 'Lenguado Planca con ensalada', 'pescado',1);
INSERT INTO PLATOS VALUES (1103, 'Corvina', 18.50, 'Corvina Planca con ensalada', 'pescado',1);
INSERT INTO PLATOS VALUES (1104, 'Rape', 18.50, 'Rape Planca con ensalada', 'pescado',1);
INSERT INTO PLATOS VALUES (1201, 'Gamba', 24.00, 'Gambas Cocida', 'pescado',1);
INSERT INTO PLATOS VALUES (1202, 'Langostino', 18.00, 'Langostino Cocido', 'pescado',1);
INSERT INTO PLATOS VALUES (1203, 'Cigalas', 21.50, 'Cigalas Cocida', 'pescado',1);
INSERT INTO PLATOS VALUES (1301, 'Solomillo Iberico', 13.00, 'Solomillo Iberico con patatas fritas', 'carne',1);
INSERT INTO PLATOS VALUES (1302, 'Presa Iberica', 15.00, 'Presa Iberica con patatas fritas', 'carne',1);
INSERT INTO PLATOS VALUES (1303, 'Lagarto Iberico', 13.50, 'Lagarto Iberico con patatas fritas', 'carne',1);
INSERT INTO PLATOS VALUES (1304, 'Lomo Ibrerico', 14.00, 'Lomo Ibrerico con patatas fritas', 'carne',1);
INSERT INTO PLATOS VALUES (1401, 'Caña Lomo', 18.00, 'Caña Lomo', 'chacina',1);
INSERT INTO PLATOS VALUES (1402, 'Jamon Iberico', 18.00, 'Jamon Iberico', 'chacina',1);
INSERT INTO PLATOS VALUES (1403, 'Salchichon', 16.00, 'Salchichon', 'chacina',1);
INSERT INTO PLATOS VALUES (1404, 'Variado Iberico', 21.00, 'Variado Iberico', 'chacina',1);
INSERT INTO PLATOS VALUES (1405, 'Queso Manchego', 12.00, 'Queso Manchego', 'chacina',1);
INSERT INTO PLATOS VALUES (1001, 'Choco frito', 10.50, 'choco', 'pescado',2);
INSERT INTO PLATOS VALUES (1002, 'Adobo frito', 10.50, 'Cazon Adobado', 'pescado',2);
INSERT INTO PLATOS VALUES (1003, 'Pijotas', 12.50, 'Pijota fritas', 'pescado',2);
INSERT INTO PLATOS VALUES (1004, 'Boquerones', 14.50, 'Boquerones fritos', 'pescado',2);
INSERT INTO PLATOS VALUES (1005, 'Acedias', 16.50, 'Acedias fritas', 'pescado',2);
INSERT INTO PLATOS VALUES (1106, 'Rape Frito', 15.50, 'Rape Frito', 'pescado',2);
INSERT INTO PLATOS VALUES (1101, 'Pez Espada', 18.50, 'Pez Espada Planca con ensalada', 'pescado',2);
INSERT INTO PLATOS VALUES (1102, 'Lenguado', 18.50, 'Lenguado Planca con ensalada', 'pescado',2);
INSERT INTO PLATOS VALUES (1103, 'Corvina', 18.50, 'Corvina Planca con ensalada', 'pescado',2);
INSERT INTO PLATOS VALUES (1104, 'Rape', 18.50, 'Rape Planca con ensalada', 'pescado',2);
INSERT INTO PLATOS VALUES (1201, 'Gamba', 24.00, 'Gambas Cocida', 'pescado',2);
INSERT INTO PLATOS VALUES (1202, 'Langostino', 18.00, 'Langostino Cocido', 'pescado',2);
INSERT INTO PLATOS VALUES (1203, 'Cigalas', 21.50, 'Cigalas Cocida', 'pescado',2);
INSERT INTO PLATOS VALUES (1301, 'Solomillo Iberico', 13.00, 'Solomillo Iberico con patatas fritas', 'carne',2);
INSERT INTO PLATOS VALUES (1302, 'Presa Iberica', 15.00, 'Presa Iberica con patatas fritas', 'carne',2);
INSERT INTO PLATOS VALUES (1303, 'Lagarto Iberico', 13.50, 'Lagarto Iberico con patatas fritas', 'carne',2);
INSERT INTO PLATOS VALUES (1304, 'Lomo Ibrerico', 14.00, 'Lomo Ibrerico con patatas fritas', 'carne',2);
INSERT INTO PLATOS VALUES (1401, 'Caña Lomo', 18.00, 'Caña Lomo', 'chacina',2);
INSERT INTO PLATOS VALUES (1402, 'Jamon Iberico', 18.00, 'Jamon Iberico', 'chacina',2);
INSERT INTO PLATOS VALUES (1403, 'Salchichon', 16.00, 'Salchichon', 'chacina',2);
INSERT INTO PLATOS VALUES (1404, 'Variado Iberico', 21.00, 'Variado Iberico', 'chacina',2);
INSERT INTO PLATOS VALUES (1405, 'Queso Manchego', 12.00, 'Queso Manchego', 'chacina',2);
INSERT INTO PLATOS VALUES (1001, 'Choco frito', 10.50, 'choco', 'pescado',3);
INSERT INTO PLATOS VALUES (1002, 'Adobo frito', 10.50, 'Cazon Adobado', 'pescado',3);
INSERT INTO PLATOS VALUES (1003, 'Pijotas', 12.50, 'Pijota fritas', 'pescado',3);
INSERT INTO PLATOS VALUES (1004, 'Boquerones', 14.50, 'Boquerones fritos', 'pescado',3);
INSERT INTO PLATOS VALUES (1005, 'Acedias', 16.50, 'Acedias fritas', 'pescado',3);
INSERT INTO PLATOS VALUES (1106, 'Rape Frito', 15.50, 'Rape Frito', 'pescado',3);
INSERT INTO PLATOS VALUES (1101, 'Pez Espada', 18.50, 'Pez Espada Planca con ensalada', 'pescado',3);
INSERT INTO PLATOS VALUES (1102, 'Lenguado', 18.50, 'Lenguado Planca con ensalada', 'pescado',3);
INSERT INTO PLATOS VALUES (1103, 'Corvina', 18.50, 'Corvina Planca con ensalada', 'pescado',3);
INSERT INTO PLATOS VALUES (1104, 'Rape', 18.50, 'Rape Planca con ensalada', 'pescado',3);
INSERT INTO PLATOS VALUES (1201, 'Gamba', 24.00, 'Gambas Cocida', 'pescado',3);
INSERT INTO PLATOS VALUES (1202, 'Langostino', 18.00, 'Langostino Cocido', 'pescado',3);
INSERT INTO PLATOS VALUES (1203, 'Cigalas', 21.50, 'Cigalas Cocida', 'pescado',3);
INSERT INTO PLATOS VALUES (1301, 'Solomillo Iberico', 13.00, 'Solomillo Iberico con patatas fritas', 'carne',3);
INSERT INTO PLATOS VALUES (1302, 'Presa Iberica', 15.00, 'Presa Iberica con patatas fritas', 'carne',3);
INSERT INTO PLATOS VALUES (1303, 'Lagarto Iberico', 13.50, 'Lagarto Iberico con patatas fritas', 'carne',3);
INSERT INTO PLATOS VALUES (1304, 'Lomo Ibrerico', 14.00, 'Lomo Ibrerico con patatas fritas', 'carne',3);
INSERT INTO PLATOS VALUES (1401, 'Caña Lomo', 18.00, 'Caña Lomo', 'chacina',3);
INSERT INTO PLATOS VALUES (1402, 'Jamon Iberico', 18.00, 'Jamon Iberico', 'chacina',3);
INSERT INTO PLATOS VALUES (1403, 'Salchichon', 16.00, 'Salchichon', 'chacina',3);
INSERT INTO PLATOS VALUES (1404, 'Variado Iberico', 21.00, 'Variado Iberico', 'chacina',3);
INSERT INTO PLATOS VALUES (1405, 'Queso Manchego', 12.00, 'Queso Manchego', 'chacina',3);
INSERT INTO PLATOS VALUES (1001, 'Choco frito', 10.50, 'choco', 'pescado',4);
INSERT INTO PLATOS VALUES (1002, 'Adobo frito', 10.50, 'Cazon Adobado', 'pescado',4);
INSERT INTO PLATOS VALUES (1003, 'Pijotas', 12.50, 'Pijota fritas', 'pescado',4);
INSERT INTO PLATOS VALUES (1004, 'Boquerones', 14.50, 'Boquerones fritos', 'pescado',4);
INSERT INTO PLATOS VALUES (1005, 'Acedias', 16.50, 'Acedias fritas', 'pescado',4);
INSERT INTO PLATOS VALUES (1106, 'Rape Frito', 15.50, 'Rape Frito', 'pescado',4);
INSERT INTO PLATOS VALUES (1101, 'Pez Espada', 18.50, 'Pez Espada Planca con ensalada', 'pescado',4);
INSERT INTO PLATOS VALUES (1102, 'Lenguado', 18.50, 'Lenguado Planca con ensalada', 'pescado',4);
INSERT INTO PLATOS VALUES (1103, 'Corvina', 18.50, 'Corvina Planca con ensalada', 'pescado',4);
INSERT INTO PLATOS VALUES (1104, 'Rape', 18.50, 'Rape Planca con ensalada', 'pescado',4);
INSERT INTO PLATOS VALUES (1201, 'Gamba', 24.00, 'Gambas Cocida', 'pescado',4);
INSERT INTO PLATOS VALUES (1202, 'Langostino', 18.00, 'Langostino Cocido', 'pescado',4);
INSERT INTO PLATOS VALUES (1203, 'Cigalas', 21.50, 'Cigalas Cocida', 'pescado',4);
INSERT INTO PLATOS VALUES (1301, 'Solomillo Iberico', 13.00, 'Solomillo Iberico con patatas fritas', 'carne',4);
INSERT INTO PLATOS VALUES (1302, 'Presa Iberica', 15.00, 'Presa Iberica con patatas fritas', 'carne',4);
INSERT INTO PLATOS VALUES (1303, 'Lagarto Iberico', 13.50, 'Lagarto Iberico con patatas fritas', 'carne',4);
INSERT INTO PLATOS VALUES (1304, 'Lomo Ibrerico', 14.00, 'Lomo Ibrerico con patatas fritas', 'carne',4);
INSERT INTO PLATOS VALUES (1401, 'Caña Lomo', 18.00, 'Caña Lomo', 'chacina',4);
INSERT INTO PLATOS VALUES (1402, 'Jamon Iberico', 18.00, 'Jamon Iberico', 'chacina',4);
INSERT INTO PLATOS VALUES (1403, 'Salchichon', 16.00, 'Salchichon', 'chacina',4);
INSERT INTO PLATOS VALUES (1404, 'Variado Iberico', 21.00, 'Variado Iberico', 'chacina',4);
INSERT INTO PLATOS VALUES (1405, 'Queso Manchego', 12.00, 'Queso Manchego', 'chacina',4);
INSERT INTO PLATOS VALUES (1001, 'Choco frito', 10.50, 'choco', 'pescado',5);
INSERT INTO PLATOS VALUES (1002, 'Adobo frito', 10.50, 'Cazon Adobado', 'pescado',5);
INSERT INTO PLATOS VALUES (1003, 'Pijotas', 12.50, 'Pijota fritas', 'pescado',5);
INSERT INTO PLATOS VALUES (1004, 'Boquerones', 14.50, 'Boquerones fritos', 'pescado',5);
INSERT INTO PLATOS VALUES (1005, 'Acedias', 16.50, 'Acedias fritas', 'pescado',5);
INSERT INTO PLATOS VALUES (1106, 'Rape Frito', 15.50, 'Rape Frito', 'pescado',5);
INSERT INTO PLATOS VALUES (1101, 'Pez Espada', 18.50, 'Pez Espada Planca con ensalada', 'pescado',5);
INSERT INTO PLATOS VALUES (1102, 'Lenguado', 18.50, 'Lenguado Planca con ensalada', 'pescado',5);
INSERT INTO PLATOS VALUES (1103, 'Corvina', 18.50, 'Corvina Planca con ensalada', 'pescado',5);
INSERT INTO PLATOS VALUES (1104, 'Rape', 18.50, 'Rape Planca con ensalada', 'pescado',5);
INSERT INTO PLATOS VALUES (1201, 'Gamba', 24.00, 'Gambas Cocida', 'pescado',5);
INSERT INTO PLATOS VALUES (1202, 'Langostino', 18.00, 'Langostino Cocido', 'pescado',5);
INSERT INTO PLATOS VALUES (1203, 'Cigalas', 21.50, 'Cigalas Cocida', 'pescado',5);
INSERT INTO PLATOS VALUES (1301, 'Solomillo Iberico', 13.00, 'Solomillo Iberico con patatas fritas', 'carne',5);
INSERT INTO PLATOS VALUES (1302, 'Presa Iberica', 15.00, 'Presa Iberica con patatas fritas', 'carne',5);
INSERT INTO PLATOS VALUES (1303, 'Lagarto Iberico', 13.50, 'Lagarto Iberico con patatas fritas', 'carne',5);
INSERT INTO PLATOS VALUES (1304, 'Lomo Ibrerico', 14.00, 'Lomo Ibrerico con patatas fritas', 'carne',5);
INSERT INTO PLATOS VALUES (1401, 'Caña Lomo', 18.00, 'Caña Lomo', 'chacina',5);
INSERT INTO PLATOS VALUES (1402, 'Jamon Iberico', 18.00, 'Jamon Iberico', 'chacina',5);
INSERT INTO PLATOS VALUES (1403, 'Salchichon', 16.00, 'Salchichon', 'chacina',5);
INSERT INTO PLATOS VALUES (1404, 'Variado Iberico', 21.00, 'Variado Iberico', 'chacina',5);
INSERT INTO PLATOS VALUES (1405, 'Queso Manchego', 12.00, 'Queso Manchego', 'chacina',5);



