-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 17:20:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoRestaurante
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoRestaurante` ;

-- -----------------------------------------------------
-- Schema ProyectoRestaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoRestaurante` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoRestaurante` ;

-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Cliente` (
  `DNI` VARCHAR(9) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Codigo_Postal` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Cod_Cliente` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Cod_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Descuentos` (
  `Cod_Descuento` INT NOT NULL,
  `Dia` VARCHAR(45) NULL,
  `Porcentaje_Descuento` INT NULL,
  PRIMARY KEY (`Cod_Descuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Restaurante` (
  `Cod_Restaurante` INT NOT NULL AUTO_INCREMENT,
  `Localidad` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `Cod_Postal` DECIMAL(5,0) NULL,
  `Telefono` DECIMAL(9,0) NULL,
  PRIMARY KEY (`Cod_Restaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Pedidos` (
  `Codigo_Pedidos` INT NOT NULL AUTO_INCREMENT,
  `Estado` ENUM('Rechazado', 'Entregado', 'Enviado') NOT NULL,
  `Fecha_hora_Pedido` DATE NOT NULL,
  `Fecha_hora_Entrega` DATE NOT NULL,
  `Importe total` INT NULL,
  `Descuentos_Cod_Descuento` INT NOT NULL,
  `Cliente_Cod_Cliente` INT NOT NULL,
  `Restaurante_Cod_Restaurante` INT NOT NULL,
  PRIMARY KEY (`Codigo_Pedidos`),
  INDEX `fk_Pedidos_Descuentos1_idx` (`Descuentos_Cod_Descuento` ASC) VISIBLE,
  INDEX `fk_Pedidos_Cliente1_idx` (`Cliente_Cod_Cliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_Restaurante1_idx` (`Restaurante_Cod_Restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Descuentos1`
    FOREIGN KEY (`Descuentos_Cod_Descuento`)
    REFERENCES `ProyectoRestaurante`.`Descuentos` (`Cod_Descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`Cliente_Cod_Cliente`)
    REFERENCES `ProyectoRestaurante`.`Cliente` (`Cod_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Restaurante1`
    FOREIGN KEY (`Restaurante_Cod_Restaurante`)
    REFERENCES `ProyectoRestaurante`.`Restaurante` (`Cod_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Platos` (
  `Cod_Platos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL(4,2) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Cod_Restaurante` INT NOT NULL,
  PRIMARY KEY (`Cod_Platos`, `Cod_Restaurante`),
  INDEX `fk_Platos_Restaurante1_idx` (`Cod_Restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_Platos_Restaurante1`
    FOREIGN KEY (`Cod_Restaurante`)
    REFERENCES `ProyectoRestaurante`.`Restaurante` (`Cod_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`ticket` (
  `Platos_Cod_Platos` INT NOT NULL,
  `Unidades` INT NULL,
  `Pedidos_Codigo_Pedidos` INT NOT NULL,
  `Cod_Ticket` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Platos_has_Pedidos_Platos1_idx` (`Platos_Cod_Platos` ASC) VISIBLE,
  INDEX `fk_ticket_Pedidos1_idx` (`Pedidos_Codigo_Pedidos` ASC) VISIBLE,
  PRIMARY KEY (`Cod_Ticket`),
  CONSTRAINT `fk_Platos_has_Pedidos_Platos1`
    FOREIGN KEY (`Platos_Cod_Platos`)
    REFERENCES `ProyectoRestaurante`.`Platos` (`Cod_Platos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_Pedidos1`
    FOREIGN KEY (`Pedidos_Codigo_Pedidos`)
    REFERENCES `ProyectoRestaurante`.`Pedidos` (`Codigo_Pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Horarios` (
  `DIa` VARCHAR(20) NOT NULL,
  `Hora_apertura` VARCHAR(45) NULL,
  `Hora_cierre` VARCHAR(45) NULL,
  `Restaurante_Cod_Restaurante` INT NOT NULL,
  PRIMARY KEY (`DIa`, `Restaurante_Cod_Restaurante`),
  INDEX `fk_Horarios_Restaurante1_idx` (`Restaurante_Cod_Restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_Horarios_Restaurante1`
    FOREIGN KEY (`Restaurante_Cod_Restaurante`)
    REFERENCES `ProyectoRestaurante`.`Restaurante` (`Cod_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Area reparto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Area reparto` (
  `Codigo_Postal` DECIMAL(5,0) NOT NULL,
  `Cod_Restaurante` INT NOT NULL,
  PRIMARY KEY (`Codigo_Postal`),
  INDEX `fk_Area reparto_Restaurante1_idx` (`Cod_Restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_Area reparto_Restaurante1`
    FOREIGN KEY (`Cod_Restaurante`)
    REFERENCES `ProyectoRestaurante`.`Restaurante` (`Cod_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
